### ISSUE TITLE
PIP-seq

### ISSUE THREAD

**Issue by lakigigar** [IGVF/seqspec#11]
Would be great to add a PIP-seq spec: https://www.nature.com/articles/s41587-023-01685-z

**Comment by dbrg77** [comment]
On my to-do list. Hopefully, will start looking into it in two weeks when this term ends :-)

**Comment by dbrg77** [comment]
Turns out more complicated than I expected. I have a draft here: 

https://teichlab.github.io/scg_lib_structs/methods_html/PIP-seq_rc.html

The basic idea should be correct, but the sequence details are not right at the moment. In the method of PIP-seq, they cite the [Delley2021](https://www.nature.com/articles/s41598-021-90255-x) paper. The current HTML is created using the cell barcodes from the Delley2021 paper. However, when I check some example data of PIP-seq (SRR19180490) and Human-Mouse Mix of the T2 kit from https://www.fluentbio.com/datasets/, the barcodes and read structures are not consistent with the HTML.

Will investigate more with their data and add a seqspec when things are clear.

In the meantime, people can get an idea about how PIP-seq roughly works by looking at the HTML page.

**Comment by dbrg77** [comment]
Okay, I have finished this and the library structures seem to be consistent with the data from the paper and example data on the FluentBio website.

As you can see, I'm not really familiar with PRs. I intended to submit them as separate PRs, but eventually, ISSAAC-seq, PIP-seq V2 and V3 all end up in one PR.

Oh well ...

**Comment by sbooeshaghi** [comment]
This has been completed and merged into the code base. Thank you @dbrg77 !

See https://github.com/IGVF/seqspec/pull/12

**Comment by lakigigar** [comment]
Thanks @dbrg77!
