### ISSUE TITLE
Linker is not a region_type

### ISSUE THREAD

**Issue by emattei** [IGVF/seqspec#14]
In the example specs there is a `region_type` called `linker1`
https://github.com/IGVF/seqspec/blob/0d408a38cec4e632f85a20bd95c26c56ad1ac1dc/specs/SHARE-seq/spec.yaml#LL457C1-L457C1

But it doesn't seem to be an allowed type https://github.com/IGVF/seqspec/blob/main/docs/SPECIFICATION.md

What is the correct `type` to use.

Moreover, `region_type` has a number to it but I assume that that spec it is outdated and it should be `region_type: linker` and `region_id: linker-1`

**Comment by sbooeshaghi** [comment]
You're right- that is not an allowed region_type. I've updated the seqspec schema so that `seqspec check` will validate `region_type` and `sequence_type` against a controlled vocabulary so the tool will now catch bugs like this. 

And yes- your suggested change is the right one. I've updated the spec you've referenced in the repo. Thank you!
